# Generated by Django 5.0.7 on 2024-08-02 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_blog_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
